### ISSUE TITLE
Possible to reformat a disk that has a Linux fs on it

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-proxy#104]
**What happened**:
The implementation of IsVolumeFormatted only checks for ntfs filesystem, and it returns false if it doesn't find ntfs. That means it returns unformatted if there's a linux filesystem on it, and then subsequently calling FormatVolume can override the filesystem.

More discussion in https://app.slack.com/client/T09NY5SBT/CN5JCCW31/thread/C8EJ01Z46-1603793388.212200

**What you expected to happen**:
Format should error if a filesystem is already on the disk.

**Comment by jingxu97** [comment]
Some discussion from CSI windows meeting. We could consider to add another check, MBR in sector 0 through golang disk reads. Expectation is a fresh provisioned disk has all zeroes. Otherwise, consider disk is already formatted.

The concern is that it might result in false positive. Some disk might returns random data even though it is not formatted. With this logic, volume will not be formatted anymore. 

cc @marosset

**Comment by jingxu97** [comment]
this issue is fixed by https://github.com/kubernetes-csi/csi-proxy/pull/127

**Comment by andyzhangx** [comment]
if you try a linux ext4 file system disk on the windows node with v1.0.2 version, the disk would be still formatted, expected behavior is mount error since we cannot mount ext4 disk on windows node.

Reopen this issue since original PR does not fix the issue.

**Comment by andyzhangx** [comment]
is there a way to detect ext4 file system on Windows node?
 
CloudCopilot
No, it is not possible to detect an ext4 file system on a Windows node natively. Windows does not support the ext4 file system by default, and there is no built-in tool or command that can detect it.
However, there are third-party tools available that can help you detect and access ext4 file systems on Windows. One such tool is Ext2Fsd, which is an open-source file system driver for Windows that allows you to access Linux ext2, ext3, and ext4 file systems from within Windows.
Keep in mind that using third-party tools to access file systems can be risky, as it may lead to data loss or corruption. It is always recommended to back up your data before attempting to access file systems using third-party tools.
