### ISSUE TITLE
does csi-proxy support domain name resolve?

### ISSUE THREAD

**Issue by junneyang** [kubernetes-csi/csi-proxy#107]
https://github.com/kubernetes-csi/csi-driver-smb/issues/160

windows: 2019
k8s: v1.17.2

when i use
`source: \sfs-nas1.cn-south-1c.xxx.com\share-2d58d4ca`
is does not work, but when i use
`source: \10.12.13.5\share-2d58d4ca`
it works

thanks for your help!

**Comment by andyzhangx** [comment]
cc @jingxu97 @ddebroy
