### ISSUE TITLE
Password field should be hidden in the SMB NewSmbGlobalMappingRequest Proto

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-csi/csi-proxy#142]
This field should be hidden https://github.com/kubernetes-csi/csi-proxy/blob/c2495301dc4209759d986af0c40b5e1584f71866/client/api/smb/v1beta2/api.proto#L34

- [ ] Investigate how to update csi-proxy's build process to include additional proto plugins like in https://github.com/container-storage-interface/spec/blob/da58351ba3d7baf850877be3425e76ff30645d33/lib/go/Makefile#L134-L144
- [ ] Extend the FieldOptions field like https://github.com/container-storage-interface/spec/blob/da58351ba3d7baf850877be3425e76ff30645d33/csi.proto#L23-L32
- [ ] Use the field option in the `password` field

**Comment by Kartik494** [comment]
Hi @mauriciopoppe As far as i get it here you are asking for updating password field [in](https://github.com/kubernetes-csi/csi-proxy/blob/c2495301dc4209759d986af0c40b5e1584f71866/client/api/smb/v1beta2/api.proto#L34) as a secret? or we can make a new function that would call the encrypted password?

**Comment by mauriciopoppe** [comment]
hey @Kartik494, this to hide the `password` field while the gRPC request is in transit, it's about adding an annotation in the proto file to the secret field like

https://github.com/container-storage-interface/spec/blob/da58351ba3d7baf850877be3425e76ff30645d33/csi.proto#L686-L695

```
map<string, string> secrets = 2 [(csi_secret) = true];
```

I've updated the top description with a tasklist of the things that we need

**Comment by Kartik494** [comment]
I would like to work on this
/assign

**Comment by Kartik494** [comment]
> * [ ]  Investigate how to update csi-proxy's build process to include additional proto plugins like in https://github.com/container-storage-interface/spec/blob/da58351ba3d7baf850877be3425e76ff30645d33/lib/go/Makefile#L134-L144

I have tried to compile api.proto with protoc installed by apt.But this is not generating api.pb.go file , then I looked into [comment](https://github.com/grpc-ecosystem/grpc-gateway/issues/422#issuecomment-409809309) and tried for protoc 3.19.3 and working without including in makefile

**Comment by mauriciopoppe** [comment]
hey @Kartik494, there's a test [here](https://github.com/kubernetes-csi/csi-proxy/blob/master/.github/workflows/windows.yml) that installs a version of protobuf that works, locally I used:

```
protoc --version
libprotoc 3.12.4
```

**Comment by Kartik494** [comment]
Sure i will give a try on this again and i will let you know if that works.
Thanks

**Comment by mauriciopoppe** [comment]
In one of the CSI Windows meetings we saw that the secret annotation is used by [csi-lib-utils](https://github.com/kubernetes-csi/csi-lib-utils/blob/f9b3af56d1f16431977b9e3387a52f13687513f8/protosanitizer/protosanitizer.go) when logging a request, in CSI Proxy we aren't using this library and we don't log the requests by default.

We agreed that if we make sure that we don't have log statements in the codebase that are logging the requests (and their secrets if they have them) then we don't need to add that annotation to the field, I apologize for not finding out this before.

/close
