### ISSUE TITLE
Daemonset deployment failing - ImagePullBackOff

### ISSUE THREAD

**Issue by marciogmorales** [kubernetes-csi/csi-proxy#161]
**What happened**: Container images not available on the repository.

**What you expected to happen**:
Successfully pull the following images:

org/csi-driver:win-v1
gke.gcr.io/csi-node-driver-registrar:win-v1

**How to reproduce it**:

Just run the Daemonset deployment YAML file on the readme.

**Anything else we need to know?**:

The deployment YAML file uses a ServiceAccount called csi-node-sa which needs to be created before running the Daemontset deployment, otherwise it will fail. There is no instruction saying that needs to be created.

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g. from /etc/os-release): WIndows Server 2019 LTSC
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Kubectl describe pod attached (log.txt)
[Log.txt](https://github.com/kubernetes-csi/csi-proxy/files/6778505/Log.txt)

**Comment by mauriciopoppe** [comment]
Thanks for the report! Our README looks like it's out of date, the sig storage images were changed to be served from a different location, please use `k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0`, `org/csi-driver:win-v1` should be driver that you want to deploy on your cluster e.g. for the GCE PD CSI Driver gke.gcr.io/gcp-compute-persistent-disk-csi-driver

**Comment by marciogmorales** [comment]
Thanks Mauricio, it worked.
Now I'm receiving this log at the pod creation:

kubectl logs podname

error: a container name must be specified for pod csi-storage-node-win-8sg45, choose one of: [csi-driver-registrar csi-driver]

**Comment by marciogmorales** [comment]
Thanks, it worked.
Now I'm receiving the following error on the csi-driver-registrar:

processstarttime.go:43] Could not get process start time, could not read /proc: CreateFile /proc: The system cannot find the file specified.

Log attached.
[csi-driver-registrar.txt](https://github.com/kubernetes-csi/csi-proxy/files/6779926/csi-driver-registrar.txt)

**Comment by mauriciopoppe** [comment]
The README has a sample implementation with some placeholders (although the placeholders are not very well defined), I think it depends on how this sidecar is used in your driver, for example the configuration for GCE PD CSI driver in windows nodes is https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/master/deploy/kubernetes/base/node_windows/node.yaml
