### ISSUE TITLE
Image csi-driver can not pull

### ISSUE THREAD

**Issue by tomsunyu** [kubernetes-csi/csi-proxy#169]
Hi, I execute this command:
**docker pull org/csi-driver:win-v1**

Then the following error reports have occurred:
Error response from daemon: pull access denied for org/csi-driver, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

But I can pull the image k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0

So how to pull the image org/csi-driver:win-v1 ?

**Comment by mauriciopoppe** [comment]
hey @tomsunyu, sorry for the late reply, `org/csi-driver:win-v1` is just a placeholder for the location of the CSI Driver, for example for the GCE PD CSI Driver the path to the latest stable version is `gke.gcr.io/gcp-compute-persistent-disk-csi-driver:v1.2.0-gke.8`

**Comment by tomsunyu** [comment]
Thanks. But my kubernetes environment is not on the public cloud such as GCE, and get errors:
I0813 18:26:07.026160   18664 main.go:73] Driver vendor version v1.3.0
I0813 18:26:07.026649   18664 gce.go:84] Using GCE provider config <nil>
W0813 18:26:07.039818   18664 gce.go:137] GOOGLE_APPLICATION_CREDENTIALS env var not set
I0813 18:26:07.039818   18664 gce.go:139] Using DefaultTokenSource <nil>
F0813 18:26:07.039818   18664 main.go:103] Failed to get cloud provider: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

I have datacenters and phisical servers, so I build a kubernetes cluster with several windows nodes. So how can I find the image such as **gke.gcr.io/gcp-compute-persistent-disk-csi-driver:v1.2.0-gke.8**

**Comment by mauriciopoppe** [comment]
I understand, `org/csi-driver:win-v1` is just a placeholder to the CSI Driver that you want to install,  you have to pick a CSI Driver depending on your use case and the hardware that you have available in your datacenter, for example (and this is not implying that you have the resources to support this) if you have an NFS Server and want to make it available to your kubernetes cluster you could use the https://github.com/kubernetes-csi/csi-driver-nfs, I know of a few CSI Drivers with Windows support that are described in the [CSI Proxy GA blogpost](https://kubernetes.io/blog/2021/08/09/csi-windows-support-with-csi-proxy-reaches-ga/):

- AWS EBS CSI Driver
- Azure Disk CSI Driver
- GCE PD CSI Driver
- SMB CSI Driver

**Comment by ddebroy** [comment]
> I have datacenters and phisical servers, so I build a kubernete cluster with several windows nodes.
hey @tomsunyu what kind of persistent storage solution are you deploying for your cluster? Does the storage solution surface SMB that the Windows containers can use?

**Comment by tomsunyu** [comment]
So far, I haven't found a reliable solution.
