### ISSUE TITLE
make build doesnot generate csi-proxy.exe 

### ISSUE THREAD

**Issue by pvreddy37** [kubernetes-csi/csi-proxy#267]
HI

We are trying to clone git:   git clone https://github.com/kubernetes-csi/csi-proxy

and then run  the command **make build** in windows We don't get the expected csi-proxy.exe. 

Here is the log :

makefile:25: warning: overriding commands for target `test-go'
release-tools/build.make:227: warning: ignoring old commands for target `test-go'
makefile:31: warning: overriding commands for target `test-vet'
release-tools/build.make:233: warning: ignoring old commands for target `test-vet'
make: Nothing to be done for `build'.

Can you please let us know if there is any other way to download  csi-proxy.exe. . We are trying to set up CSI-SMB for windows node and we see that this service is not present or started by default in RKE2.

**Comment by pvreddy37** [comment]
@alexander-ding  Can you help here

**Comment by pvreddy37** [comment]
@alexander-ding  Can you help here

**Comment by alexander-ding** [comment]
We're in the middle of bumping to v2. The master branch is used for active development, and the stable v1 code is housed on the `v1.x` branch. Also, the latest tagged version is available as a GitHub release [here](https://github.com/kubernetes-csi/csi-proxy/releases/tag/v1.1.2). You can use either source code and build from there.

**Comment by mauriciopoppe** [comment]
@pvreddy37 we restored master to point to the client/server model, new development is going to happen in this branch https://github.com/kubernetes-csi/csi-proxy/tree/library-development.
