### ISSUE TITLE
release-tools subtree is broken

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/csi-proxy#37]
Because this repo overrode the Makefile to not use the release-tools/build.make rules, it never ran any of the verify-* scripts during pull jobs, such as verify-subtree.sh.

This let https://github.com/kubernetes-csi/csi-proxy/pull/22 merge, which directly modified release-tools/, which we don't want.

@pohly, I remember we had this problem in another repo and we relaxed the verify script to allow reverts to work. Can we do that here? Revert https://github.com/kubernetes-csi/csi-proxy/pull/22, and then update release-tools + enable the verify scripts?

**Comment by msau42** [comment]
cc @kkmsft @jingxu97 @ddebroy

**Comment by pohly** [comment]
> I remember we had this problem in another repo and we relaxed the verify script to allow reverts to work.

Yes, we did: https://github.com/kubernetes-csi/csi-release-tools/commit/cc564f929a4e32a829d35272533242b94797aa22

> Can we do that here? Revert #22, and then update release-tools + enable the verify scripts?

That should work. Basically do a `git rm -rf release-tools`, `git commit`, then import as described in https://github.com/kubernetes-csi/csi-release-tools/blob/master/README.md#sharing-and-updating

**Comment by kkmsft** [comment]
/close
Via #38
