### ISSUE TITLE
Remove dependency on Diskutil.exe used by GetDiskNumberByName API 

### ISSUE THREAD

**Issue by jingxu97** [kubernetes-csi/csi-proxy#51]
Currently, PD disk id is not available through powershell command. As a workaround we use a C code disktutil.exe to get Page 83 ID based mapping. We want to have a Go version of the C code of diskutil.exe using go-bindings (https://medium.com/jettech/breaking-all-the-rules-using-go-to-call-windows-api-2cbfd8c79724)

**Comment by jingxu97** [comment]
cc @ksubrmnn

**Comment by ksubrmnn** [comment]
@ddebroy @jingxu97 is there a reason we don't just do (Get-Disk -FriendlyName $name).Number

**Comment by ddebroy** [comment]
@ksubrmnn the disk number is the physical disk number assigned by the Windows OS storage stack. What we need here is Page 83 ID that the hardware (or cloud software backing a AzureDisk/GCE-PD) returns - and something that unfortunately powershell/wmi around disk/storage does not implement today. 

This is the C code backing diskutil: https://gist.github.com/ddebroy/f43cceb2af256bd425bad4502bd8b099. It returns the OS disk number with a given SCSI Page 83 ID.

The following IOCTLs and structs will need to be converted to Go code and issued on a disk handle to query the Page 83 ID:
`IOCTL_STORAGE_QUERY_PROPERTY`
`STORAGE_PROPERTY_QUERY` along with nested structs 
`STORAGE_DEVICE_ID_DESCRIPTOR` along with nested structs

To obtain the disk handles to send the IOCTLs to, you will need to enumerate all disk devices that the OS disk stack has seen and that aspect can be done through powershell. So you don't need the code from diskutil above that calls into the SetupDi APIs.
