### ISSUE TITLE
containers cannot connect to csi-proxy named pipes with containerd on Windows

### ISSUE THREAD

**Issue by marosset** [kubernetes-csi/csi-proxy#55]
Containers are failing to create when pods that mount in named pipes on Windows when running with containerd with the following error

` Warning  Failed     14s                kubelet, 3336k8s00000000  Error: failed to generate container "fa55d3efa900b24520fa7a528e61dece7b7694dbf444a2654d846b2b3840a30f" spec: failed to generate spec: failed to resolve symlink "": CreateFile \\.\pipe\csi-proxy-filesystem-v1alpha1: All pipe instances are busy.`

This works when Windows nodes are configured with docker.

**Comment by marosset** [comment]
Looks like containerd for Windows still needs add support for mounting named pipes
https://github.com/containerd/cri/blob/ae8200bf93e9eda91d1c8b40dc14257ec0bdea02/pkg/containerd/opts/spec_windows.go#L103

**Comment by marosset** [comment]
https://github.com/containerd/containerd/issues/4320

**Comment by ddebroy** [comment]
@marosset given https://github.com/containerd/cri/pull/1511 is now in, any chance you can test if the containerd based Windows container scenario works now?

**Comment by marosset** [comment]
@ddebroy I had validated this worked when the fix went in. I can enable some periodic jobs as well so we'll have the test results on test-grid. We can close this issue after those results are up.

**Comment by ddebroy** [comment]
@marosset do we still need to track this issue?

**Comment by marosset** [comment]
@chewong and I have been working on periodic jobs that validate CSI-proxy with azure-file/azure-disk drivers on Azure.
I was hoping to close this once we had that CI signal set up but things are taking a bit longer to get set up there.
I'm fine closing this now since I have manually validated this a number of times.

/close
