### ISSUE TITLE
Formatting and mounting a volume is much slower on windows than on linux

### ISSUE THREAD

**Issue by manueltellez** [kubernetes-csi/csi-proxy#56]
What happened:

CSI volume operations are much slower on windows using csi-proxy than on Linux.

What you expected to happen:
Performance of storage operations on Linux and the ones being performed by csi-proxy on Windows to be comparable. While slower performance is expected we have seen a 3x multiplier when compared to the same operations on a Linux node. 

We see multiple process invocations using os.exec. Another observation is the creation of the PowerShell runspace and session for the distinct commands.

**Comment by andyzhangx** [comment]
is this related to CSI volume?

**Comment by ddebroy** [comment]
According to @manueltellez https://github.com/kubernetes/kubernetes/pull/91307 helped with the issue above quite a bit.
