### ISSUE TITLE
Add a way to query BIOS DMI in csi-proxy

### ISSUE THREAD

**Issue by ddebroy** [kubernetes-csi/csi-proxy#78]
**What happened**:
To support CSI plugins like vsphere, csi-proxy needs to be able to surface BIOS DMI details to the plugin. Please enable this support, potentially through a new `system` API group. This should do something identical to: https://github.com/kubernetes/kubernetes/blob/103e926604de6f79161b78af3e792d0ed282bc06/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere_util_windows.go#L29

**What you expected to happen**:
There is no way to surface BIOS DMI details today.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: NA
- Kubernetes version (use `kubectl version`): NA
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`): NA
- Install tools:
- Others:

**Comment by ddebroy** [comment]
https://github.com/kubernetes-csi/csi-proxy/pull/81 addressing this

**Comment by rhockenbury** [comment]
It looks like #81 was merged so this issue can likely be closed. 

Do you know if there has been any progress on supporting vsphere CSI with csi-proxy?
