### ISSUE TITLE
Invalid version error on `go get -v github.com/kubernetes-csi/csi-proxy`

### ISSUE THREAD

**Issue by boddumanohar** [kubernetes-csi/csi-proxy#79]
**What happened**:
I am currently experimenting with CSI-Proxy, so in my package, I tried to get csi-proxy using:
```
go get -v github.com/kubernetes-csi/csi-proxy
```
I am using windows 10 and go version is: `go version go1.15.2 windows/amd64`
I get this error:
```
$ go get github.com/kubernetes-csi/csi-proxy
go: github.com/kubernetes-csi/csi-proxy upgrade => v0.2.1
go get: github.com/kubernetes-csi/csi-proxy@v0.2.1 requires
        github.com/kubernetes-csi/csi-proxy/client@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**What you expected to happen**:
I am expecting the go get to complete.

**How to reproduce it**:
On windows machine with go version 1.15, do:  `go get -v github.com/kubernetes-csi/csi-proxy`
**Anything else we need to know?**:

**Environment**:
- CSI Driver version: latest master
- Kubernetes version (use `kubectl version`): -
- OS (e.g. from /etc/os-release): Windows
- Kernel (e.g. `uname -a`): 10
- Install tools:
- Others: go version: 1.15

**Comment by ddebroy** [comment]
Can you please try ` go get github.com/kubernetes-csi/csi-proxy/client@v0.2.1` assuming you want to develop a CSI plugin that uses csi-proxy? Note that as a plugin author, your dependency should be csi-proxy/client API module rather than the rest of the csi-proxy binary.
