### ISSUE TITLE
CSI-Proxy crashes with error: panic: The service process could not connect to the service controller when -windows-service argument is passed 

### ISSUE THREAD

**Issue by boddumanohar** [kubernetes-csi/csi-proxy#80]
**What happened**:
I tried to run CSI-Proxy with the argument `-windows-service` but then it crashes with this log.
```
panic: The service process could not connect to the service controller.

goroutine 1 [running]:
main.main()
        C:/Users/manoh/github/csi-proxy/cmd/csi-proxy/main.go:41 +0x27c
```

**What you expected to happen**:
I am expecting the binary to run as windows service.

**How to reproduce it**:
the csi-proxy binary: https://kubernetesartifacts.azureedge.net/csi-proxy/v0.2.1/binaries/csi-proxy.tar.gz with the argument `-windows-service`

**Environment**:
- CSI Driver version: v0.2.1
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release): windows 10
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc: @andyzhangx

**Comment by ddebroy** [comment]
From Jing, this repros when you have an instance of csi-proxy running already.
